### ISSUE TITLE
[CRASH] TypeError: Cannot find function desktopButton in object

### ISSUE THREAD

**Issue by DrunkenPoney** [DeltaNedas/ui-lib#1]
The game crashes on startup. It crashes during the _initial_ game load at around 80%.

Mindustry version: 104.6
OS: Ubuntu 20.04

<details>
<summary>Crash report</summary>
<pre><code>org.mozilla.javascript.EcmaError: TypeError: Cannot find function desktopButton in object [object Object]. (areas#138)
	at org.mozilla.javascript.ScriptRuntime.constructError(ScriptRuntime.java:4256)
	at org.mozilla.javascript.ScriptRuntime.constructError(ScriptRuntime.java:4234)
	at org.mozilla.javascript.ScriptRuntime.typeError(ScriptRuntime.java:4267)
	at org.mozilla.javascript.ScriptRuntime.typeError2(ScriptRuntime.java:4286)
	at org.mozilla.javascript.ScriptRuntime.notFunctionError(ScriptRuntime.java:4358)
	at org.mozilla.javascript.ScriptRuntime.getPropFunctionAndThisHelper(ScriptRuntime.java:2580)
	at org.mozilla.javascript.ScriptRuntime.getPropFunctionAndThis(ScriptRuntime.java:2562)
	at org.mozilla.javascript.gen.areas_7._c_anonymous_21(areas:138)
	at org.mozilla.javascript.gen.areas_7.call(areas)
	at org.mozilla.javascript.optimizer.OptRuntime.call1(OptRuntime.java:45)
	at org.mozilla.javascript.gen.library_6._c_anonymous_4(library:59)
	at org.mozilla.javascript.gen.library_6.call(library)
	at org.mozilla.javascript.ArrowFunction.call(ArrowFunction.java:43)
	at org.mozilla.javascript.optimizer.OptRuntime.callProp0(OptRuntime.java:98)
	at org.mozilla.javascript.gen.main_js_5._c_anonymous_4(main.js:43)
	at org.mozilla.javascript.gen.main_js_5.call(main.js)
	at org.mozilla.javascript.ContextFactory.doTopCall(ContextFactory.java:409)
	at org.mozilla.javascript.ScriptRuntime.doTopCall(ScriptRuntime.java:3566)
	at org.mozilla.javascript.gen.main_js_5.call(main.js)
	at org.mozilla.javascript.ArrowFunction.call(ArrowFunction.java:43)
	at org.mozilla.javascript.Context.lambda$call$0(Context.java:543)
	at org.mozilla.javascript.Context.call(Context.java:552)
	at org.mozilla.javascript.Context.call(Context.java:543)
	at org.mozilla.javascript.JavaAdapter.callMethod(JavaAdapter.java:589)
	at adapter1.run(<adapter>)
	at arc.Events.lambda$on$0(Events.java:17)
	at arc.Events.lambda$fire$2(Events.java:26)
	at arc.struct.Array.each(Array.java:181)
	at arc.Events.fire(Events.java:26)
	at arc.Events.fire(Events.java:21)
	at mindustry.ClientLauncher.update(ClientLauncher.java:133)
	at arc.backend.sdl.SdlApplication.listen(SdlApplication.java:158)
	at arc.backend.sdl.SdlApplication.loop(SdlApplication.java:146)
	at arc.backend.sdl.SdlApplication.<init>(SdlApplication.java:52)
	at mindustry.desktop.DesktopLauncher.main(DesktopLauncher.java:46)
</code></pre>
</details>

**Comment by DeltaNedas** [comment]
oh yes im very silly
ill actually make the button now
