### ISSUE TITLE
ReferenceError: "func" is not defined

### ISSUE THREAD

**Issue by CesarScur** [DeltaNedas/ui-lib#4]
Error after adding `DeltaNedas/ui-lib` mod. Also has `DeltaNedas/speed` mod.

Stacktrace:
```java
org.mozilla.javascript.EcmaError: ReferenceError: "func" is not defined. (library#74)
	at org.mozilla.javascript.ScriptRuntime.constructError(ScriptRuntime.java:4256)
	at org.mozilla.javascript.ScriptRuntime.constructError(ScriptRuntime.java:4234)
	at org.mozilla.javascript.ScriptRuntime.notFoundError(ScriptRuntime.java:4324)
	at org.mozilla.javascript.ScriptRuntime.nameOrFunction(ScriptRuntime.java:2001)
	at org.mozilla.javascript.ScriptRuntime.getNameFunctionAndThis(ScriptRuntime.java:2468)
	at org.mozilla.javascript.optimizer.OptRuntime.callName(OptRuntime.java:74)
	at org.mozilla.javascript.gen.library_6._c_anonymous_4(library:74)
	at org.mozilla.javascript.gen.library_6.call(library)
	at org.mozilla.javascript.ArrowFunction.call(ArrowFunction.java:43)
	at org.mozilla.javascript.optimizer.OptRuntime.callProp0(OptRuntime.java:98)
	at org.mozilla.javascript.gen.main_js_8._c_anonymous_4(main.js:43)
	at org.mozilla.javascript.gen.main_js_8.call(main.js)
	at org.mozilla.javascript.ContextFactory.doTopCall(ContextFactory.java:409)
	at org.mozilla.javascript.ScriptRuntime.doTopCall(ScriptRuntime.java:3566)
	at org.mozilla.javascript.gen.main_js_8.call(main.js)
	at org.mozilla.javascript.ArrowFunction.call(ArrowFunction.java:43)
	at org.mozilla.javascript.Context.lambda$call$0(Context.java:543)
	at org.mozilla.javascript.Context.call(Context.java:552)
	at org.mozilla.javascript.Context.call(Context.java:543)
	at org.mozilla.javascript.JavaAdapter.callMethod(JavaAdapter.java:589)
	at adapter3.run(<adapter>)
	at arc.Events.lambda$on$0(Events.java:17)
	at arc.Events.lambda$fire$2(Events.java:26)
	at arc.struct.Array.each(Array.java:175)
	at arc.Events.fire(Events.java:26)
	at arc.Events.fire(Events.java:21)
	at mindustry.ClientLauncher.update(ClientLauncher.java:131)
	at arc.backend.sdl.SdlApplication.listen(SdlApplication.java:158)
	at arc.backend.sdl.SdlApplication.loop(SdlApplication.java:146)
	at arc.backend.sdl.SdlApplication.<init>(SdlApplication.java:52)
	at mindustry.desktop.DesktopLauncher.main(DesktopLauncher.java:46)
```

**Comment by DeltaNedas** [comment]
what version of mindustry and mod
this doesn't happen for me on 6.0

**Comment by CesarScur** [comment]
build 104

**Comment by DeltaNedas** [comment]
update to 104.10, func definitely exists
